### ISSUE TITLE
Fetching the incorrect serial number of device

### ISSUE THREAD

**Issue by chuang0221** [tomwang221812/sample_qtop#1]
### Description:

The function ```get_adb_device_as_options``` may get the incorrect serial number of device, because of the following lines:
```shell
 57    for line in $(adb devices | tail -n +2 | tr -d '\tdevices' | head --lines=-1);

 84    for line in $(adb devices | tail -n +2 | tr -d '\tdevices' | head --lines=-1);
```
If the device's serial number contains any character in "devices", the character will be deleted due to this line ```tr -d '\tdevices'```.

### Scenario:

For example, my device's serial number is "b9b64bea". However, the function gets "b9b64ba" as serial number.

**Comment by tomwang221812** [comment]
[Fixed](https://github.com/tomwang221812/sample_qtop/blob/main/sample_qtop_adb#L76)
